# 1. Setup & Data Loading

In [10]:
import pandas as pd
import numpy as np



# Citire CSV-uri
clubs = pd.read_csv('../data/raw/clubs.csv')
players = pd.read_csv('../data/raw/players.csv')
valuations = pd.read_csv('../data/raw/player_valuations.csv')
appearances = pd.read_csv('../data/raw/appearances.csv')
club_games = pd.read_csv('../data/raw/club_games.csv')

# 2. Player Filtering & Target Definition
Calculate player age, filter active cohorts (last season >= 2025, age <= 36), and ensure valid market valuations and positions.

In [11]:

# Creare coloana Age pentru jucatori
players['date_of_birth'] = pd.to_datetime(players['date_of_birth'])
players['age'] = np.floor(((pd.Timestamp.now() - players['date_of_birth']).dt.days / 365.25)).astype('Int64')

# Jucatori care merita considerati, jucatorii de peste 36 de ani nu mai au o cota de piata relevanta
players_active = players[(players['last_season'] >= 2025) & (players['age'] <= 36)]

# Top Jucatori
players_active.sort_values('market_value_in_eur', ascending = False)[['name', 'date_of_birth', 'age', 'market_value_in_eur']].head(10)

                        name date_of_birth  age  market_value_in_eur
24652         Erling Haaland    2000-07-21   26          200000000.0
40874           Lamine Yamal    2007-07-13   19          200000000.0
20901          Kylian Mbappé    1998-12-20   27          180000000.0
34578                  Pedri    2002-11-25   23          150000000.0
30170          Michael Olise    2001-12-12   24          150000000.0
27234                Vitinha    2000-02-13   26          140000000.0
22490        Vinicius Junior    2000-07-12   26          140000000.0
34163             João Neves    2004-09-27   22          140000000.0
27768  Khvicha Kvaratskhelia    2001-02-12   25          140000000.0
30789        Jude Bellingham    2003-06-29   23          130000000.0

# 3. Missing Value Analysis & Target Filtering

In [12]:

# Numarul de jucatori cu valori nule per coloana
players_active.isna().sum()

player_id                                   0
first_name                               1056
last_name                                   0
name                                        0
last_season                                 0
current_club_id                             0
player_code                                 0
country_of_birth                         2035
city_of_birth                            2016
country_of_citizenship                      0
date_of_birth                               0
sub_position                              147
position                                    0
foot                                     1912
height_in_cm                             1022
contract_expiration_date                 2752
agent_name                               6452
image_url                                   0
international_caps                       4601
international_goals                      4601
current_national_team_id                13227
url                                         0
current_club_domestic_competition_id     2991
current_club_name                        2991
market_value_in_eur                      1445
highest_market_value_in_eur              1445
age                                         0
dtype: int64

In [13]:

# jucatori care au cota de piata
players_with_value = players_active[
    (players_active['market_value_in_eur'].notna()) &
    (players_active['sub_position'].notna())
]
# grupare dupa pozitii
players_with_value.groupby('sub_position').agg(
    mean_market_value = ('market_value_in_eur', 'mean'),
    max_market_value = ('market_value_in_eur', 'max'),
    number_of_players = ('market_value_in_eur', 'count')
).sort_values('mean_market_value', ascending = False)

                    mean_market_value  max_market_value  number_of_players
sub_position
Second Striker           3.988889e+06        28000000.0                 63
Right Winger             3.925250e+06       200000000.0               1221
Attacking Midfield       3.914536e+06       130000000.0               1283
Central Midfield         3.912608e+06       150000000.0               1844
Left Winger              3.759450e+06       140000000.0               1309
Centre-Forward           3.601565e+06       200000000.0               2169
Centre-Back              3.046371e+06       100000000.0               3082
Defensive Midfield       3.039005e+06       140000000.0               1468
Left-Back                2.586210e+06        80000000.0               1269
Right-Back               2.434566e+06        80000000.0               1359
Right Midfield           1.690376e+06        23000000.0                213
Left Midfield            1.586919e+06        25000000.0                172
Goalkeeper               1.514090e+06        45000000.0               1802

# 4. Market Value Normalization & Age Breakdown

In [14]:

# adaugam o coloana in care avem valorile in milioane de euro
players_with_value['market_value_in_m'] = players['market_value_in_eur'] / 1_000_000

# grupare dupa varsta
players_with_value.groupby('age').agg(
    mean_market_value = ('market_value_in_m', 'mean'),
    number_of_players = ('market_value_in_m', 'count'),
    max_market_value = ('market_value_in_m', 'max')
).sort_values('age', ascending = True)

     mean_market_value  number_of_players  max_market_value
age
16            4.916667                  9              30.0
17            1.614352                 54              17.0
18            2.882838                266              60.0
19            3.259134                543             200.0
20            3.117743                853              80.0
21            3.117105               1076             120.0
22            3.361310               1260             140.0
23            3.877402               1351             150.0
24            4.184982               1361             150.0
25            4.099653               1383             140.0
26            4.152859               1371             200.0
27            4.279607               1272             180.0
28            3.376650               1203              90.0
29            3.102811               1119             100.0
30            2.175091                929              50.0
31            1.691565                802              35.0
32            1.318750                708              35.0
33            1.039414                614              60.0
34            0.837206                467              22.0
35            0.583696                345              15.0
36            0.308470                268               3.0

# 5. Merging Club Context & Recent Match Stats (Last 3 Years)

In [15]:


# Pasul 3 - Feature Engineering - Merge-uim clubs cu players
clubs_subset = clubs[['club_id', 'name', 'domestic_competition_id', 'squad_size']]
clubs_subset = clubs_subset.rename(columns = {'name': 'club_name'})
players_stats = players_with_value.merge(
    clubs_subset,
    left_on = 'current_club_id',
    right_on = 'club_id',
    how = 'left'
)
# luam meciurile din ultimii 3 ani
appearances['date'] = pd.to_datetime(appearances['date'])
recent_appearances = appearances[appearances['date'].dt.year >= 2023] # mai tarziu o sa revenim si o sa le numaram pe sezoane, nu pe ultimele 3 si atat
players_subset = players_stats[['player_id', 'name', 'country_of_citizenship', 'sub_position']]
player_stats = recent_appearances.groupby('player_id').agg(
    goals = ('goals', 'sum'),
    assists = ('assists', 'sum'),
    minutes_played = ('minutes_played', 'sum'),
)
player_stats = player_stats.reset_index()
players_stats = players_stats.merge(
    player_stats[['player_id', 'goals', 'assists', 'minutes_played']],
    on='player_id',
    how='left'
)
players_stats[['goals', 'assists', 'minutes_played', 'international_caps', 'international_goals']] = players_stats[['goals', 'assists', 'minutes_played', 'international_caps', 'international_goals']].fillna(0)

ml_data = players_stats[
    ['sub_position', 'foot', 'height_in_cm', 'age', 'country_of_citizenship', 'domestic_competition_id', 'squad_size',
     'goals', 'assists', 'minutes_played', 'international_caps', 'international_goals', 'market_value_in_m', 'player_id',
     'current_club_id'
    ]
]
ml_data = ml_data.dropna()

# 6. Feature Engineering: Attacking Rates (Per 90) & Clean Sheets

In [16]:

# creare statistica goals + assists

ml_data['contributions_per_90'] = (
    (ml_data['goals'] + ml_data['assists']) / ml_data['minutes_played'] * 90
).fillna(0)

# cream clean sheets pt fundasi si portari
app_games = pd.merge(recent_appearances,
                     club_games,
                     left_on = ['game_id', 'player_club_id'],
                     right_on = ['game_id', 'club_id'],
                     how = 'inner'
                     )
app_games['is_clean_sheet'] = ((app_games['opponent_goals'] == 0) & (app_games['minutes_played'] > 0)).astype(int)
clean_sheets_df = app_games.groupby('player_id').agg(
    clean_sheets = ('is_clean_sheet', 'sum')
).reset_index()
ml_data = ml_data.merge(
    clean_sheets_df,
    on = 'player_id',
    how = 'left'
).fillna(0)

defensive_positions = [
    'Goalkeeper', 'Centre-Back', 'Left-Back', 'Right-Back', 'Defensive Midfield'
]

ml_data.loc[~ml_data['sub_position'].isin(defensive_positions), 'clean_sheets'] = 0

# 7. Feature Engineering: Age-Decay Potential Scores

In [17]:

# calculam o valoare pentru potentialul fiecarui jucator in fnuctie de varsta
# 29 de ani = apogeul, mai apoi valoarea incepe sa mai scada
# youth_minutes_score = minutes_played * max(0, 29 - age)
ml_data['youth_minutes_score'] = ml_data['minutes_played'] * (29 - ml_data['age']).clip(lower=0)

# calculam statistica goals + assists in functie de varsta
ml_data['contributions_score'] = (ml_data['goals'] + ml_data['assists']) * (29 - ml_data['age']).clip(lower = 0)

# calculam statistica clean sheets in functie de varsta pentru pozitiile mai defensive

ml_data['clean_sheets_score'] = (ml_data['clean_sheets']) * (29 - ml_data['age']).clip(lower = 0)

# 8. European Competition Stats (UCL) & Dataset Export

In [18]:

# calculam statisticile pentru ucl
ucl_stats = appearances[appearances['competition_id'] == 'CL'].groupby('player_id').agg(
    ucl_minutes_played = ('minutes_played', 'sum'),
    ucl_goals = ('goals', 'sum'),
    ucl_assists = ('assists', 'sum')
).reset_index()

ml_data = ml_data.merge(
    ucl_stats,
    on = 'player_id',
    how = 'left'
).fillna(0)


ml_data.to_csv('../data/processed/ml_data_ready.csv', index = False)